#pragma once
namespace webdata {
inline const J translations=J::parse(R"SABKADATA({
  "bn": {
    "account": "অ্যাকাউন্ট",
    "addToCart": "ব্যাগে যোগ করুন",
    "addedToCart": "ব্যাগে যোগ করা হয়েছে",
    "adminPortal": "অ্যাডমিন ও হার্ডওয়্যার",
    "adminStateAdvancer": "অর্ডার স্ট্যাটাস পরিবর্তন (ডেমো)",
    "aiAssistant": "এআই সহকারী",
    "allCategories": "সব ক্যাটাগরি",
    "appTitle": "সবকা বাজার",
    "audioReadAloud": "পড়ে শোনান",
    "buyNow": "এখনই কিনুন",
    "callAttendant": "সহকারীকে ডাকুন",
    "cancelOrder": "অর্ডার বাতিল করুন",
    "cancelSuccess": "অর্ডার বাতিল করা হয়েছে।",
    "cannotCancel": "এই অবস্থায় অর্ডার বাতিল করা যাবে না।",
    "cardPayment": "ডেবিট কার্ড",
    "cart": "ব্যাগ (কার্ট)",
    "cashOnDelivery": "ক্যাশ অন ডেলিভারি (COD)",
    "categories": "ক্যাটাগরি",
    "checkout": "চেকআউট",
    "confirmCancel": "আপনি কি নিশ্চিত যে অর্ডার বাতিল করতে চান?",
    "deliveryAddress": "ডেলিভারি ঠিকানা",
    "deliveryFee": "ডেলিভারি চার্জ",
    "easyMode": "সহজ কেনাকাটা মোড",
    "easyModeActive": "সহজ মোড চালু",
    "easyModeDesc": "বড় লেখা ও সহজে ব্যবহারযোগ্য বোতাম",
    "emptyCart": "আপনার ব্যাগ খালি",
    "emptyCartAction": "পণ্য দেখুন",
    "featuredProducts": "জনপ্রিয় পণ্য",
    "freeDelivery": "ফ্রি",
    "freeDeliveryThreshold": "₹৪৯৯ টাকার উপরে ফ্রি ডেলিভারি",
    "goToCart": "কার্টে যান",
    "gst": "জিএসটি (যুক্ত)",
    "help": "সহায়তা কেন্দ্র",
    "inStock": "স্টকে আছে",
    "kioskHelpTriggered": "কিয়স্কে সহায়তা চাওয়া হয়েছে!",
    "login": "লগ ইন / সাইন আপ",
    "logout": "লগ আউট",
    "onlyLeft": "মাত্র {count}টি অবশিষ্ট",
    "orderId": "অর্ডার নম্বর",
    "orderSuccess": "অর্ডার সফল হয়েছে!",
    "orders": "আমার অর্ডার",
    "outOfStock": "স্টক শেষ",
    "paymentMethod": "পেমেন্ট মাধ্যম",
    "placeOrder": "অর্ডার নিশ্চিত করুন",
    "proceedToCheckout": "কেনার জন্য এগিয়ে যান",
    "raiseTicket": "অভিযোগ জানান",
    "searchButton": "খুঁজুন",
    "searchPlaceholder": "পণ্য বা স্থানীয় নাম খুঁজুন (যেমন: তেজপাতা, হলুদ, মোবাইল)...",
    "smsCallback": "কলব্যাকের অনুরোধ",
    "stateRecommendation": "আপনার রাজ্যের জন্য ভাষা: ",
    "stateSelector": "রাজ্য নির্বাচন করুন",
    "statusCancelled": "বাতিল",
    "statusConfirmed": "গৃহীত",
    "statusDelivered": "পৌঁছে গেছে",
    "statusOutForDelivery": "ডেলিভারির জন্য বেরিয়েছে",
    "statusPacked": "প্যাক হয়েছে",
    "statusPlaced": "অর্ডার দেওয়া হয়েছে",
    "statusShipped": "পাঠানো হয়েছে",
    "subtotal": "মোট দাম",
    "tagline": "সবার জন্য সহজ ও সুবিধাজনক কেনাকাটা",
    "totalPayable": "মোট প্রদেয়",
    "trackOrder": "অর্ডার ট্র্যাক করুন",
    "upiPayment": "ইউপিআই / কিউআর",
    "viewDetails": "বিস্তারিত দেখুন",
    "voiceListening": "শুনছি... নাম বলুন",
    "voiceRecognized": "শনাক্ত হয়েছে: ",
    "voiceSearch": "ভয়েস সার্চ",
    "wishlist": "পছন্দের তালিকা"
  },
  "en": {
    "account": "Account",
    "addToCart": "Add to Cart",
    "addedToCart": "Added to Cart",
    "adminPortal": "Admin & Hardware",
    "adminStateAdvancer": "Advance Order State (Demo)",
    "aiAssistant": "AI Support Assistant",
    "allCategories": "All Categories",
    "appTitle": "Sabka Bazzar",
    "audioReadAloud": "Read aloud",
    "buyNow": "Buy Now",
    "callAttendant": "Call Store Attendant",
    "cancelOrder": "Cancel Order",
    "cancelSuccess": "Order has been cancelled.",
    "cannotCancel": "Order cannot be cancelled at this stage.",
    "cardPayment": "RuPay / Debit Card (Mock Simulation)",
    "cart": "Cart",
    "cashOnDelivery": "Cash on Delivery (Pay at Doorstep)",
    "categories": "Categories",
    "checkout": "Checkout",
    "confirmCancel": "Are you sure you want to cancel this order?",
    "deliveryAddress": "Delivery Address",
    "deliveryFee": "Delivery Fee",
    "easyMode": "Easy Shopping Mode",
    "easyModeActive": "Easy Mode Active (Large Text)",
    "easyModeDesc": "Simple view, big buttons & voice assistance for comfortable shopping",
    "emptyCart": "Your cart is empty",
    "emptyCartAction": "Explore Products",
    "featuredProducts": "Popular Products",
    "freeDelivery": "FREE",
    "freeDeliveryThreshold": "Free delivery on orders above ₹499",
    "goToCart": "Go to Cart",
    "gst": "Demo tax (5%, added)",
    "help": "1-Click Help",
    "inStock": "In Stock",
    "kioskHelpTriggered": "Assistance Requested at Kiosk!",
    "login": "Login / Register",
    "logout": "Logout",
    "onlyLeft": "Only {count} left in stock",
    "orderId": "Order ID",
    "orderSuccess": "Order Placed Successfully!",
    "orders": "My Orders",
    "outOfStock": "Out of Stock",
    "paymentMethod": "Payment Option",
    "placeOrder": "Place Order Now",
    "proceedToCheckout": "Proceed to Buy",
    "raiseTicket": "Raise Support Ticket",
    "searchButton": "Search",
    "searchPlaceholder": "Search products, local names (e.g. tej patta, haldi, phone)...",
    "smsCallback": "Request SMS / Phone Callback",
    "stateRecommendation": "Suggested for your state: ",
    "stateSelector": "Select Your State / Region",
    "statusCancelled": "Cancelled",
    "statusConfirmed": "Confirmed",
    "statusDelivered": "Delivered",
    "statusOutForDelivery": "Out for Delivery",
    "statusPacked": "Packed",
    "statusPlaced": "Placed",
    "statusShipped": "Shipped",
    "subtotal": "Items Subtotal",
    "tagline": "Ghar mein generations chaar, pasand ke rang hazaar — sabki shopping ka ek thikana, Sabka Bazaar!",
    "totalPayable": "Total Payable",
    "trackOrder": "Track Order Progress",
    "upiPayment": "UPI / QR Code (Mock Simulation)",
    "viewDetails": "View Details",
    "voiceListening": "Listening... Speak your item name now",
    "voiceRecognized": "Recognized: ",
    "voiceSearch": "Voice Search",
    "wishlist": "Wishlist"
  },
  "gu": {
    "account": "ખાતું",
    "addToCart": "કાર્ટમાં ઉમેરો",
    "addedToCart": "કાર્ટમાં ઉમેર્યું",
    "adminPortal": "એડમિન પોર્ટલ",
    "adminStateAdvancer": "ઓર્ડર સ્થિતિ આગળ વધારો (ડેમો)",
    "aiAssistant": "AI સહાયક",
    "allCategories": "બધી શ્રેણીઓ",
    "appTitle": "સબકા બાઝાર",
    "audioReadAloud": "વાંચી સંભળાવો",
    "buyNow": "હમણાં ખરીદો",
    "callAttendant": "મદદનીશને બોલાવો",
    "cancelOrder": "ઓર્ડર રદ કરો",
    "cancelSuccess": "ઓર્ડર રદ થયો છે.",
    "cannotCancel": "ઓર્ડર રદ કરી શકાતો નથી.",
    "cardPayment": "ડેબિટ કાર્ડ",
    "cart": "કાર્ટ",
    "cashOnDelivery": "કેશ ઓન ડિલિવરી (COD)",
    "categories": "શ્રેણીઓ",
    "checkout": "ચેકઆઉટ",
    "confirmCancel": "શું તમે ઓર્ડર રદ કરવા માંગો છો?",
    "deliveryAddress": "ડિલિવરી સરનામું",
    "deliveryFee": "ડિલિવરી ચાર્જ",
    "easyMode": "સરળ ખરીદી મોડ",
    "easyModeActive": "સરળ મોડ સક્રિય",
    "easyModeDesc": "મોટા અક્ષરો અને સરળ બટનો",
    "emptyCart": "તમારી કાર્ટ ખાલી છે",
    "emptyCartAction": "વસ્તુઓ જુઓ",
    "featuredProducts": "લોકપ્રિય વસ્તુઓ",
    "freeDelivery": "મફત",
    "freeDeliveryThreshold": "₹499 થી વધુ પર મફત ડિલિવરી",
    "goToCart": "કાર્ટમાં જાઓ",
    "gst": "જીએસટી (સમાવિષ્ટ)",
    "help": "મદદ",
    "inStock": "સ્ટોકમાં છે",
    "kioskHelpTriggered": "મદદની માંગણી!",
    "login": "લૉગ ઇન / સાઇન અપ",
    "logout": "લૉગ આઉટ",
    "onlyLeft": "માત્ર {count} બાકી",
    "orderId": "ઓર્ડર નંબર",
    "orderSuccess": "ઓર્ડર સફળ થયો!",
    "orders": "મારા ઓર્ડર",
    "outOfStock": "સ્ટોક ખલાસ",
    "paymentMethod": "ચૂકવણી પદ્ધતિ",
    "placeOrder": "ઓર્ડર કરો",
    "proceedToCheckout": "ખરીદી આગળ વધારો",
    "raiseTicket": "ફરિયાદ નોંધાવો",
    "searchButton": "શોધો",
    "searchPlaceholder": "વસ્તુઓ અથવા દેશી નામ શોધો (દા.ત. તમાલપત્ર, હળદર)...",
    "smsCallback": "કૉલ બેક વિનંતી",
    "stateRecommendation": "તમારા રાજ્ય માટે ભલામણ કરેલ ભાષા: ",
    "stateSelector": "રાજ્ય પસંદ કરો",
    "statusCancelled": "રદ કર્યો",
    "statusConfirmed": "સ્વીકાર્યો",
    "statusDelivered": "પહોંચી ગયો",
    "statusOutForDelivery": "ડિલિવરી માટે નીકળ્યો",
    "statusPacked": "પેક થયો",
    "statusPlaced": "ઓર્ડર મળ્યો",
    "statusShipped": "મોકલી દીધો",
    "subtotal": "કુલ રકમ",
    "tagline": "સૌ માટે સુલભ અને સરળ ખરીદી",
    "totalPayable": "કુલ ચૂકવવાપાત્ર",
    "trackOrder": "ઓર્ડર ટ્રેક કરો",
    "upiPayment": "યુપીઆઇ / ક્યૂઆર",
    "viewDetails": "વિગત જુઓ",
    "voiceListening": "સાંભળી રહ્યા છીએ...",
    "voiceRecognized": "ઓળખાયું: ",
    "voiceSearch": "અવાજથી શોધો",
    "wishlist": "પસંદગી યાદી"
  },
  "hi": {
    "account": "खाता",
    "addToCart": "थैले में डालें",
    "addedToCart": "थैले में जोड़ा गया",
    "adminPortal": "एडमिन व हार्डवेयर",
    "adminStateAdvancer": "ऑर्डर स्थिति आगे बढ़ाएं (डेमो)",
    "aiAssistant": "एआई सहायता केंद्र",
    "allCategories": "सभी श्रेणियां",
    "appTitle": "सबका बाज़ार",
    "audioReadAloud": "बोलकर सुनाएं",
    "buyNow": "तुरंत खरीदें",
    "callAttendant": "सहायक को बुलाएं",
    "cancelOrder": "ऑर्डर रद्द करें",
    "cancelSuccess": "ऑर्डर सफलतापूर्वक रद्द कर दिया गया है।",
    "cannotCancel": "इस चरण पर ऑर्डर रद्द नहीं किया जा सकता।",
    "cardPayment": "डेबिट कार्ड / रुपे कार्ड (डेमो)",
    "cart": "थैला (कार्ट)",
    "cashOnDelivery": "सामान मिलने पर नकद भुगतान (COD)",
    "categories": "श्रेणियां",
    "checkout": "चेकआउट (भुगतान)",
    "confirmCancel": "क्या आप सचमुच यह ऑर्डर रद्द करना चाहते हैं?",
    "deliveryAddress": "डिलीवरी का पता",
    "deliveryFee": "डिलीवरी शुल्क",
    "easyMode": "सुगम खरीदारी मोड",
    "easyModeActive": "सुगम मोड चालू (बड़ा फॉन्ट)",
    "easyModeDesc": "बुजुर्गों और आसान इस्तेमाल के लिए बड़े बटन और सरल स्क्रीन",
    "emptyCart": "आपका थैला खाली है",
    "emptyCartAction": "सामान देखें",
    "featuredProducts": "लोकप्रिय उत्पाद",
    "freeDelivery": "मुफ्त (FREE)",
    "freeDeliveryThreshold": "₹499 से अधिक के ऑर्डर पर मुफ्त डिलीवरी",
    "goToCart": "कार्ट पर जाएँ",
    "gst": "जीएसटी कर (शामिल)",
    "help": "1-क्लिक सहायता",
    "inStock": "उपलब्ध है",
    "kioskHelpTriggered": "कियोस्क पर सहायता की मांग हुई!",
    "login": "लॉग इन / खाता बनाएं",
    "logout": "लॉग आउट",
    "onlyLeft": "केवल {count} स्टॉक में शेष",
    "orderId": "ऑर्डर संख्या",
    "orderSuccess": "ऑर्डर सफलतापूर्वक स्वीकार हो गया!",
    "orders": "मेरे ऑर्डर",
    "outOfStock": "स्टॉक खत्म",
    "paymentMethod": "भुगतान का तरीका",
    "placeOrder": "ऑर्डर पक्का करें",
    "proceedToCheckout": "खरीदारी आगे बढ़ाएं",
    "raiseTicket": "शिकायत दर्ज करें",
    "searchButton": "खोजें",
    "searchPlaceholder": "सामान या देशी नाम खोजें (जैसे: तेज पत्ता, हल्दी, मोबाइल)...",
    "smsCallback": "एसएमएस या फोन कॉल का अनुरोध करें",
    "stateRecommendation": "आपके राज्य के लिए अनुशंसित भाषा: ",
    "stateSelector": "अपना राज्य / क्षेत्र चुनें",
    "statusCancelled": "रद्द किया गया",
    "statusConfirmed": "स्वीकृत",
    "statusDelivered": "सफलतापूर्वक प्राप्त हुआ",
    "statusOutForDelivery": "डिलीवरी के लिए निकला",
    "statusPacked": "पैक हुआ",
    "statusPlaced": "ऑर्डर दिया गया",
    "statusShipped": "भेज दिया गया",
    "subtotal": "सामान का कुल मूल्य",
    "tagline": "घर में जेनरेशन्स चार, पसंद के रंग हज़ार — सबकी शॉपिंग का एक ठिकाना, सबका बाज़ार!",
    "totalPayable": "कुल देय राशि",
    "trackOrder": "ऑर्डर की स्थिति देखें",
    "upiPayment": "यूपीआई / क्यूआर कोड (डेमो)",
    "viewDetails": "विवरण देखें",
    "voiceListening": "सुन रहे हैं... कृपया सामान का नाम बोलें",
    "voiceRecognized": "पहचाना गया: ",
    "voiceSearch": "आवाज़ से खोजें",
    "wishlist": "पसंद सूची"
  },
  "mr": {
    "account": "खाते",
    "addToCart": "कार्टमध्ये जोडा",
    "addedToCart": "कार्टमध्ये जोडले",
    "adminPortal": "अॅडमिन आणि हार्डवेअर",
    "adminStateAdvancer": "ऑर्डर स्थिती पुढे न्या (डेमो)",
    "aiAssistant": "एआय मदतनीस",
    "allCategories": "सर्व वर्ग",
    "appTitle": "सबका बाज़ार",
    "audioReadAloud": "वाचून दाखवा",
    "buyNow": "आता खरेदी करा",
    "callAttendant": "मदतनीसाला बोलवा",
    "cancelOrder": "ऑर्डर रद्द करा",
    "cancelSuccess": "ऑर्डर रद्द झाली आहे.",
    "cannotCancel": "या टप्प्यावर ऑर्डर रद्द करता येत नाही.",
    "cardPayment": "डेबिट कार्ड",
    "cart": "कार्ट",
    "cashOnDelivery": "कॅश ऑन डिलिव्हरी (COD)",
    "categories": "वर्गवारी",
    "checkout": "चेकआउट",
    "confirmCancel": "तुम्हाला नक्की ऑर्डर रद्द करायची आहे का?",
    "deliveryAddress": "डिलिव्हरी पत्ता",
    "deliveryFee": "डिलिव्हरी शुल्क",
    "easyMode": "सुलभ खरेदी मोड",
    "easyModeActive": "सुलभ मोड चालू",
    "easyModeDesc": "मोठे फॉन्ट आणि सोपी रचना",
    "emptyCart": "तुमची कार्ट रिकामी आहे",
    "emptyCartAction": "उत्पादने शोधा",
    "featuredProducts": "लोकप्रिय उत्पादने",
    "freeDelivery": "मोफत",
    "freeDeliveryThreshold": "₹४९९ वरील ऑर्डरवर मोफत डिलिव्हरी",
    "goToCart": "कार्टमध्ये जा",
    "gst": "जीएसटी (समाविष्ट)",
    "help": "१-क्लिक मदत",
    "inStock": "उपलब्ध आहे",
    "kioskHelpTriggered": "कियोस्कवर मदत मागितली गेली!",
    "login": "लॉग इन / नोंदणी",
    "logout": "लॉग आउट",
    "onlyLeft": "फक्त {count} शिल्लक",
    "orderId": "ऑर्डर क्रमांक",
    "orderSuccess": "ऑर्डर यशस्वीरित्या नोंदवली गेली!",
    "orders": "माझे ऑर्डर्स",
    "outOfStock": "साठा संपला",
    "paymentMethod": "पेमेंट पर्याय",
    "placeOrder": "ऑर्डर नोंदवा",
    "proceedToCheckout": "पुढे जा",
    "raiseTicket": "तक्रार नोंदवा",
    "searchButton": "शोधा",
    "searchPlaceholder": "उत्पादन किंवा स्थानिक नाव शोधा (उदा. तेजपत्ता, हळद, मोबाईल)...",
    "smsCallback": "कॉल बॅक विनंती",
    "stateRecommendation": "तुमच्या राज्यासाठी भाषा: ",
    "stateSelector": "राज्य निवडा",
    "statusCancelled": "रद्द केली",
    "statusConfirmed": "स्वीकृत",
    "statusDelivered": "पोहोचली",
    "statusOutForDelivery": "डिलिव्हरीसाठी बाहेर",
    "statusPacked": "पॅक झाली",
    "statusPlaced": "नोंदवली गेली",
    "statusShipped": "पाठवली",
    "subtotal": "एकूण रक्कम",
    "tagline": "सर्वांसाठी सुलभ आणि सोपी खरेदी",
    "totalPayable": "एकूण देय",
    "trackOrder": "ऑर्डर ट्रॅक करा",
    "upiPayment": "यूपीआय / क्यूआर कोड",
    "viewDetails": "तपशील पहा",
    "voiceListening": "ऐकत आहे... बोला",
    "voiceRecognized": "ओळखले: ",
    "voiceSearch": "आवाजाने शोधा",
    "wishlist": "आवडती यादी"
  },
  "or": {
    "account": "ଖାତା",
    "addToCart": "ଥଳିରେ ଯୋଡ଼ନ୍ତୁ",
    "addedToCart": "ଥଳିରେ ଯୋଡ଼ାଗଲା",
    "adminPortal": "ଆଡମିନ୍ ଓ ହାର୍ଡୱେର୍",
    "adminStateAdvancer": "ଅର୍ଡର ସ୍ଥିତି ଆଗକୁ ନିଅନ୍ତୁ (ଡେମୋ)",
    "aiAssistant": "ଏଆଇ ସହାୟତା କେନ୍ଦ୍ର",
    "allCategories": "ସମସ୍ତ ବର୍ଗ",
    "appTitle": "ସବୁଙ୍କ ବଜାର",
    "audioReadAloud": "ପଢ଼ି ଶୁଣାନ୍ତୁ",
    "buyNow": "ତୁରନ୍ତ କିଣନ୍ତୁ",
    "callAttendant": "ସହାୟକଙ୍କୁ ଡାକନ୍ତୁ",
    "cancelOrder": "ଅର୍ଡର ବାତିଲ କରନ୍ତୁ",
    "cancelSuccess": "ଅର୍ଡର ବାତିଲ କରାଯାଇଛି।",
    "cannotCancel": "ଏହି ପର୍ଯ୍ୟାୟରେ ଅର୍ଡର ବାତିଲ ସମ୍ଭବ ନୁହେଁ।",
    "cardPayment": "ରୁପେ / ଡେବିଟ୍ କାର୍ଡ (ଡେମୋ)",
    "cart": "କିଣାକିଣି ଥଳି",
    "cashOnDelivery": "ଡେଲିଭରୀ ସମୟରେ ନଗଦ (COD)",
    "categories": "ବର୍ଗସମୂହ",
    "checkout": "ଚେକ୍ ଆଉଟ୍",
    "confirmCancel": "ଆପଣ ନିଶ୍ଚିତ ଭାବେ ଏହି ଅର୍ଡର ବାତିଲ କରିବାକୁ ଚାହାଁନ୍ତି କି?",
    "deliveryAddress": "ଡେଲିଭରୀ ଠିକଣା",
    "deliveryFee": "ଡେଲିଭରୀ ଖର୍ଚ୍ଚ",
    "easyMode": "ସୁଗମ କିଣାକିଣି ମୋଡ୍",
    "easyModeActive": "ସୁଗମ ମୋଡ୍ ସକ୍ରିୟ (ବଡ଼ ଅକ୍ଷର)",
    "easyModeDesc": "ବୟସ୍କ ଏବଂ ସରଳ ବ୍ୟବହାର ପାଇଁ ବଡ଼ ବଟନ୍ ଓ ସ୍ପଷ୍ଟ ସୂଚନା",
    "emptyCart": "ଆପଣଙ୍କ ଥଳି ଖାଲି ଅଛି",
    "emptyCartAction": "ଦ୍ରବ୍ୟ ଦେଖନ୍ତୁ",
    "featuredProducts": "ଜନପ୍ରିୟ ଦ୍ରବ୍ୟ",
    "freeDelivery": "ମାଗଣା",
    "freeDeliveryThreshold": "₹୪୯୯ ରୁ ଅଧିକ ଅର୍ଡରରେ ମାଗଣା ଡେଲିଭରୀ",
    "goToCart": "କାର୍ଟକୁ ଯାଆନ୍ତୁ",
    "gst": "ଜିଏସଟି (ଅନ୍ତର୍ଭୁକ୍ତ)",
    "help": "୧-କ୍ଲିକ୍ ସହାୟତା",
    "inStock": "ଉପଲବ୍ଧ ଅଛି",
    "kioskHelpTriggered": "କିଓସ୍କରେ ସହାୟତା ଆବଶ୍ୟକ!",
    "login": "ଲଗ୍ ଇନ୍ / ପଞ୍ଜୀକରଣ",
    "logout": "ଲଗ୍ ଆଉଟ୍",
    "onlyLeft": "କେବଳ {count} ବଳକା ଅଛି",
    "orderId": "ଅର୍ଡର କ୍ରମାଙ୍କ",
    "orderSuccess": "ଅର୍ଡର ସଫଳତାର ସହ ଗୃହୀତ ହେଲା!",
    "orders": "ମୋର ଅର୍ଡର",
    "outOfStock": "ଶେଷ ହୋଇଯାଇଛି",
    "paymentMethod": "ଦେୟ ପ୍ରଣାଳୀ",
    "placeOrder": "ଅର୍ଡର ନିଶ୍ଚିତ କରନ୍ତୁ",
    "proceedToCheckout": "କିଣିବାକୁ ଆଗକୁ ବଢ଼ନ୍ତୁ",
    "raiseTicket": "ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
    "searchButton": "ଖୋଜନ୍ତୁ",
    "searchPlaceholder": "ଦ୍ରବ୍ୟ ବା ସ୍ଥାନୀୟ ନାମ ଖୋଜନ୍ତୁ (ଯେପରି: ତେଜପତ୍ର, ହଳଦୀ, ଲାପଟପ୍)...",
    "smsCallback": "ଏସଏମଏସ ବା ଫୋନ୍ କଲ୍ ଅନୁରୋଧ",
    "stateRecommendation": "ଆପଣଙ୍କ ରାଜ୍ୟ ପାଇଁ ସୁପାରିଶ ଭାଷା: ",
    "stateSelector": "ଆପଣଙ୍କ ରାଜ୍ୟ ଚୟନ କରନ୍ତୁ",
    "statusCancelled": "ବାତିଲ ହେଲା",
    "statusConfirmed": "ସ୍ୱୀକୃତ",
    "statusDelivered": "ସଫଳତାର ସହ ପହଞ୍ଚିଲା",
    "statusOutForDelivery": "ବାଣ୍ଟିବାକୁ ବାହାରିଛି",
    "statusPacked": "ପ୍ୟାକ୍ ହେଲା",
    "statusPlaced": "ଅର୍ଡର ଦିଆଗଲା",
    "statusShipped": "ପଠାଗଲା",
    "subtotal": "ମୋଟ ମୂଲ୍ୟ",
    "tagline": "ସମସ୍ତଙ୍କ ପାଇଁ ସହଜ ଏବଂ ମାତୃଭାଷାରେ କିଣାକିଣି",
    "totalPayable": "ମୋଟ ଦେୟ ରାଶି",
    "trackOrder": "ଅର୍ଡର ସ୍ଥିତି ଯାଞ୍ଚ କରନ୍ତୁ",
    "upiPayment": "ୟୁପିଆଇ / କ୍ୟୁଆର କୋଡ୍ (ଡେମୋ)",
    "viewDetails": "ବିବରଣୀ ଦେଖନ୍ତୁ",
    "voiceListening": "ଶୁଣୁଛୁ... ଦୟାକରି କୁହନ୍ତୁ",
    "voiceRecognized": "ଚିହ୍ନିତ: ",
    "voiceSearch": "କଣ୍ଠସ୍ୱରରେ ଖୋଜନ୍ତୁ",
    "wishlist": "ମନପସନ୍ଦ ତାଲିକା"
  },
  "ta": {
    "account": "கணக்கு",
    "addToCart": "கூடையில் சேர்க்கவும்",
    "addedToCart": "கூடையில் சேர்க்கப்பட்டது",
    "adminPortal": "நிர்வாகம்",
    "adminStateAdvancer": "ஆர்டர் நிலையை மாற்று (டெமோ)",
    "aiAssistant": "AI உதவி",
    "allCategories": "அனைத்து பிரிவுகள்",
    "appTitle": "சப்கா பஜார்",
    "audioReadAloud": "வாசித்து காட்டு",
    "buyNow": "உடனே வாங்கவும்",
    "callAttendant": "உதவியாளரை அழைக்கவும்",
    "cancelOrder": "ரத்து செய்",
    "cancelSuccess": "ஆர்டர் ரத்து செய்யப்பட்டது.",
    "cannotCancel": "ரத்து செய்ய முடியாது.",
    "cardPayment": "டெபிட் கார்டு",
    "cart": "கூடை",
    "cashOnDelivery": "பொருளைப் பெற்றபின் பணம்",
    "categories": "பிரிவுகள்",
    "checkout": "செக் அவுட்",
    "confirmCancel": "ரத்து செய்ய விரும்புகிறீர்களா?",
    "deliveryAddress": "முகவரி",
    "deliveryFee": "டெலிவரி கட்டணம்",
    "easyMode": "எளிதான ஷாப்பிங் முறை",
    "easyModeActive": "எளிதான முறை இயங்குகிறது",
    "easyModeDesc": "பெரிய எழுத்துக்கள் மற்றும் எளிய திரைகள்",
    "emptyCart": "கூடை காலியாக உள்ளது",
    "emptyCartAction": "பொருட்களை பார்க்கவும்",
    "featuredProducts": "பிரபலமானவை",
    "freeDelivery": "இலவசம்",
    "freeDeliveryThreshold": "₹499க்கு மேல் இலவச டெலிவரி",
    "goToCart": "கூடைக்குச் செல்லவும்",
    "gst": "ஜிஎஸ்டி",
    "help": "உதவி",
    "inStock": "கையிருப்பில் உள்ளது",
    "kioskHelpTriggered": "உதவி கோரப்பட்டது!",
    "login": "உள்நுழைய",
    "logout": "வெளியேறு",
    "onlyLeft": "{count} மட்டுமே உள்ளது",
    "orderId": "ஆர்டர் எண்",
    "orderSuccess": "ஆர்டர் வெற்றிகரமாக செய்யப்பட்டது!",
    "orders": "என் ஆர்டர்கள்",
    "outOfStock": "கையிருப்பில் இல்லை",
    "paymentMethod": "பணம் செலுத்தும் முறை",
    "placeOrder": "ஆர்டர் செய்யவும்",
    "proceedToCheckout": "வாங்க தொடரவும்",
    "raiseTicket": "புகார் பதிவு",
    "searchButton": "தேடு",
    "searchPlaceholder": "பொருட்களைத் தேடுங்கள்...",
    "smsCallback": "அழைப்பு கோரிக்கை",
    "stateRecommendation": "பரிந்துரைக்கப்பட்ட மொழி: ",
    "stateSelector": "மாநிலத்தை தேர்ந்தெடுக்கவும்",
    "statusCancelled": "ரத்து செய்யப்பட்டது",
    "statusConfirmed": "உறுதியானது",
    "statusDelivered": "வழங்கப்பட்டது",
    "statusOutForDelivery": "டெலிவரிக்கு வந்துள்ளது",
    "statusPacked": "பேக் செய்யப்பட்டது",
    "statusPlaced": "ஆர்டர் செய்யப்பட்டது",
    "statusShipped": "அனுப்பப்பட்டது",
    "subtotal": "மொத்த விலை",
    "tagline": "அனைவருக்கும் எளிதான ஷாப்பிங்",
    "totalPayable": "செலுத்த வேண்டிய தொகை",
    "trackOrder": "ஆர்டரை கண்காணிக்கவும்",
    "upiPayment": "யுபிஐ",
    "viewDetails": "விவரங்களை பார்க்கவும்",
    "voiceListening": "கேட்கிறது...",
    "voiceRecognized": "அடையாளம்: ",
    "voiceSearch": "குரல் தேடல்",
    "wishlist": "விருப்பப் பட்டியல்"
  },
  "te": {
    "account": "ఖాతా",
    "addToCart": "కార్ట్‌కు జోడించండి",
    "addedToCart": "కార్ట్‌కు జోడించబడింది",
    "adminPortal": "అడ్మిన్ పోర్టల్",
    "adminStateAdvancer": "ఆర్డర్ స్థితిని మార్చండి (డెమో)",
    "aiAssistant": "AI సహాయం",
    "allCategories": "అన్ని కేటగిరీలు",
    "appTitle": "సబ్కా బజార్",
    "audioReadAloud": "చదివి వినిపించండి",
    "buyNow": "వెంటనే కొనండి",
    "callAttendant": "సహాయకుడిని పిలవండి",
    "cancelOrder": "ఆర్డర్ రద్దు చేయండి",
    "cancelSuccess": "ఆర్డర్ రద్దు చేయబడింది.",
    "cannotCancel": "ఈ దశలో రద్దు సాధ్యం కాదు.",
    "cardPayment": "డెబిట్ కార్డు",
    "cart": "కార్ట్",
    "cashOnDelivery": "క్యాష్ ఆన్ డెలివరీ (COD)",
    "categories": "కేటగిరీలు",
    "checkout": "చెక్‌అవుట్",
    "confirmCancel": "మీరు ఆర్డర్‌ను రద్దు చేయాలనుకుంటున్నారా?",
    "deliveryAddress": "డెలివరీ చిరునామా",
    "deliveryFee": "డెలివరీ ఛార్జ్",
    "easyMode": "సులభమైన షాపింగ్ మోడ్",
    "easyModeActive": "ఈజీ మోడ్ ఆన్‌లో ఉంది",
    "easyModeDesc": "పెద్ద అక్షరాలు మరియు సులభమైన బటన్లు",
    "emptyCart": "మీ కార్ట్ ఖాళీగా ఉంది",
    "emptyCartAction": "ఉత్పత్తులను చూడండి",
    "featuredProducts": "ప్రముఖ ఉత్పత్తులు",
    "freeDelivery": "ఉచితం",
    "freeDeliveryThreshold": "₹499 పైబడి ఉచిత డెలివరీ",
    "goToCart": "కార్ట్‌కు వెళ్లండి",
    "gst": "జీఎస్టీ",
    "help": "సహాయం",
    "inStock": "అందుబాటులో ఉంది",
    "kioskHelpTriggered": "సహాయం కోరబడింది!",
    "login": "లాగిన్ / రిజిస్టర్",
    "logout": "లాగ్ అవుట్",
    "onlyLeft": "కేవలం {count} మాత్రమే మిగిలి ఉన్నాయి",
    "orderId": "ఆర్డర్ సంఖ్య",
    "orderSuccess": "ఆర్డర్ విజయవంతంగా నమోదైంది!",
    "orders": "నా ఆర్డర్లు",
    "outOfStock": "స్టాక్ అయిపోయింది",
    "paymentMethod": "చెల్లింపు విధానం",
    "placeOrder": "ఆర్డర్ ఖరారు చేయండి",
    "proceedToCheckout": "కొనుగోలుకు కొనసాగండి",
    "raiseTicket": "ఫిర్యాదు నమోదు",
    "searchButton": "వెతకండి",
    "searchPlaceholder": "ఉత్పత్తులను శోధించండి...",
    "smsCallback": "కాల్‌బ్యాక్ అభ్యర్థన",
    "stateRecommendation": "సిఫార్సు చేయబడిన భాష: ",
    "stateSelector": "రాష్ట్రాన్ని ఎంచుకోండి",
    "statusCancelled": "రద్దు చేయబడింది",
    "statusConfirmed": "ధృవీకరించబడింది",
    "statusDelivered": "డెలివరీ పూర్తయింది",
    "statusOutForDelivery": "డెలివరీకి బయలుదేరింది",
    "statusPacked": "ప్యాక్ చేయబడింది",
    "statusPlaced": "ఆర్డర్ చేయబడింది",
    "statusShipped": "రవాణా చేయబడింది",
    "subtotal": "మొత్తం ధర",
    "tagline": "అందరికీ అనువైన సులభమైన షాపింగ్",
    "totalPayable": "మొత్తం చెల్లించవలసినది",
    "trackOrder": "ఆర్డర్ ట్రాక్ చేయండి",
    "upiPayment": "యూపీఐ",
    "viewDetails": "వివరాలు చూడండి",
    "voiceListening": "వింటున్నాము...",
    "voiceRecognized": "గుర్తించబడింది: ",
    "voiceSearch": "వాయిస్ శోధన",
    "wishlist": "కోరికల జాబితా"
  }
}
)SABKADATA");
inline const J categories=J::parse(R"SABKADATA([
  {
    "icon": "Laptop",
    "id": "cat-electronics",
    "name": {
      "bn": "ইলেকট্রনিক্স",
      "en": "Electronics",
      "gu": "ઇલેક્ટ્રોનિક્સ",
      "hi": "इलेक्ट्रॉनिक्स",
      "mr": "इलेक्ट्रॉनिक्स",
      "or": "ଇଲେକ୍ଟ୍ରୋନିକ୍ସ",
      "ta": "மின்னணுவியல்",
      "te": "ఎలక్ట్రానిక్స్"
    },
    "slug": "electronics",
    "subcategories": [
      "Laptops",
      "Desktop & CPU",
      "AIO & Tower PC",
      "Tablets",
      "Mobile Covers",
      "Desktop Accessories",
      "Power Bank",
      "Gaming",
      "Healthcare",
      "Networking",
      "Earbuds"
    ]
  },
  {
    "icon": "Shirt",
    "id": "cat-fashion",
    "name": {
      "bn": "ফ্যাশন",
      "en": "Fashion",
      "gu": "ફેશન",
      "hi": "फैशन और वस्त्र",
      "mr": "फॅशन",
      "or": "ଫ୍ୟାଶନ ଓ ପୋଷାକ",
      "ta": "ஃபேஷன்",
      "te": "ఫ్యాషన్"
    },
    "slug": "fashion",
    "subcategories": [
      "Men's Tshirts & Tees",
      "Men's Kurtas",
      "Men's Jeans & Cargos",
      "Men's Tracks & Jackets",
      "Men's Watches, Belts & Wallets",
      "Men's Jewellery & Teen Styles",
      "Women's Ethnic Sets & Kurtis",
      "Women's Sarees & Blouses",
      "Women's Lehenga Cholis",
      "Women's Dresses & Tops",
      "Women's Jeans & Night Suits",
      "Women's Jewellery, Earrings & Watches",
      "Women's Handbags & Sunglasses",
      "Kids (0-2 Years)",
      "Kids (2-6 Years)",
      "Kids (6-10 Years)",
      "Kids (11-16 Years)"
    ]
  },
  {
    "icon": "Utensils",
    "id": "cat-grocery",
    "name": {
      "bn": "মুদি, খাদ্য ও স্বাস্থ্য",
      "en": "Grocery, Food & Healthcare",
      "gu": "કરિયાણું, ખાદ્ય અને આરોગ્ય",
      "hi": "किराना, खाद्य और स्वास्थ्य",
      "mr": "किराणा, खाद्य आणि आरोग्य",
      "or": "ରାସନ, ଖାଦ୍ୟ ଓ ସ୍ୱାସ୍ଥ୍ୟ",
      "ta": "மளிகை, உணவு மற்றும் சுகாதாரம்",
      "te": "కిరాణా, ఆహారం & ఆరోగ్యం"
    },
    "slug": "grocery",
    "subcategories": [
      "Spices & Condiments",
      "Flours & Grains",
      "Cooking Oils & Ghee",
      "Dry Fruits",
      "Chocolates & Sweets",
      "Preserved Foods & Pickles",
      "Hot Brews & Teas",
      "Edible Seeds",
      "Healthy Drinks",
      "Proteins & Nutrition",
      "Vitamins & Health",
      "Household Cleaning",
      "Emergency First Aid & Medical"
    ]
  },
  {
    "icon": "Footprints",
    "id": "cat-shoes",
    "name": {
      "bn": "জুতো ও চটি",
      "en": "Shoes & Sandals",
      "gu": "પગરખાં",
      "hi": "जूते और चप्पल",
      "mr": "पादत्राणे",
      "or": "ଜୋତା ଓ ଚପଲ",
      "ta": "காலணிகள்",
      "te": "పాదరక్షలు"
    },
    "slug": "shoes",
    "subcategories": [
      "Men's Casuals & Sneakers",
      "Men's Formals",
      "Men's Sandals & Sliders",
      "Men's Socks",
      "Women's Flats & Mojaris",
      "Women's Heels",
      "Women's Walking Shoes & Sliders",
      "Kids Boys Shoes"
    ]
  },
  {
    "icon": "Smartphone",
    "id": "cat-mobiles",
    "name": {
      "bn": "মোবাইল",
      "en": "Mobiles",
      "gu": "મોબાઈલ",
      "hi": "मोबाइल फोन",
      "mr": "मोबाईल्स",
      "or": "ମୋବାଇଲ ଫୋନ",
      "ta": "மொபைல் போன்கள்",
      "te": "మొబైల్ ఫోన్లు"
    },
    "slug": "mobiles",
    "subcategories": [
      "Apple iPhone",
      "Samsung Galaxy",
      "Realme",
      "Google Pixel",
      "Motorola",
      "Nothing",
      "Redmi / Xiaomi",
      "Vivo & Oppo"
    ]
  },
  {
    "icon": "Watch",
    "id": "cat-gadgets",
    "name": {
      "bn": "স্মার্ট গ্যাজেট",
      "en": "Smart Gadgets",
      "gu": "સ્માર્ટ ગેજેટ્સ",
      "hi": "स्मार्ट गैजेट्स",
      "mr": "स्मार्ट गॅजेट्स",
      "or": "ସ୍ମାର୍ଟ ଗ୍ୟାଜେଟ୍ସ",
      "ta": "ஸ்மார்ட் கேஜெட்டுகள்",
      "te": "స్మార్ట్ గాడ్జెట్లు"
    },
    "slug": "gadgets",
    "subcategories": [
      "Fitbit & Fitness Bands",
      "AirPods & TWS",
      "Bluetooth SoundBars",
      "Neckbands",
      "Smart Health Rings",
      "Smart Speakers"
    ]
  },
  {
    "icon": "Home",
    "id": "cat-home",
    "name": {
      "bn": "গৃহ ও রান্নাঘর",
      "en": "Home & Kitchen",
      "gu": "ઘર અને રસોડું",
      "hi": "घर और रसोई",
      "mr": "घर आणि स्वयंपाकघर",
      "or": "ଘର ଓ ରୋଷେଇ",
      "ta": "வீடு & சமையலறை",
      "te": "ఇల్లు & వంటగది"
    },
    "slug": "home",
    "subcategories": [
      "Gas Stoves & Cookware",
      "Bedsheets & Curtains",
      "Kitchen Storage",
      "Dinner Sets",
      "Blankets & Mattresses",
      "Wall Clocks & Decor"
    ]
  },
  {
    "icon": "Sparkles",
    "id": "cat-beauty",
    "name": {
      "bn": "সৌন্দর্য ও যত্ন",
      "en": "Beauty & Personal Care",
      "gu": "સૌંદર્ય અને વ્યક્તિગત સંભાળ",
      "hi": "सौंदर्य और व्यक्तिगत देखभाल",
      "mr": "सौंदर्य प्रसाधने",
      "or": "ସୌନ୍ଦର୍ଯ୍ୟ ଓ ବ୍ୟକ୍ତିଗତ ଯତ୍ନ",
      "ta": "அழகு சாதனங்கள்",
      "te": "సౌందర్య ఉత్పత్తులు"
    },
    "slug": "beauty",
    "subcategories": [
      "Sunscreen & Derma",
      "Face Wash & Creams",
      "Herbal Shampoos",
      "Lipsticks & Kajal",
      "Shaving Essentials",
      "Oral Care",
      "Bath & Shower"
    ]
  },
  {
    "icon": "Baby",
    "id": "cat-baby",
    "name": {
      "bn": "খেলনা ও শিশুর যত্ন",
      "en": "Toys & Baby Care",
      "gu": "રમકડાં અને બાળ સંભાળ",
      "hi": "खिलौने और शिशु देखभाल",
      "mr": "खेळणी आणि बाळ संगोपन",
      "or": "ଖେଳନା ଓ ଶିଶୁ ଯତ୍ନ",
      "ta": "பொம்மைகள் & குழந்தை பராமரிப்பு",
      "te": "బొమ్మలు & పిల్లల సంరక్షణ"
    },
    "slug": "baby",
    "subcategories": [
      "Diapers & Wipes",
      "Baby Skin Care",
      "Soft Floppy Towels",
      "Educational Wooden Toys",
      "Board Games",
      "School Backpacks & Stationery"
    ]
  },
  {
    "icon": "Activity",
    "id": "cat-sports",
    "name": {
      "bn": "খেলাধুলা ও ফিটনেস",
      "en": "Sports & Fitness",
      "gu": "રમતો અને ફિટનેસ",
      "hi": "खेल और फिटनेस",
      "mr": "खेळ आणि तंदुरुस्ती",
      "or": "ଖେଳ ଓ ଫିଟନେସ",
      "ta": "விளையாட்டு & உடற்தகுதி",
      "te": "క్రీడలు & ఫిట్నెస్"
    },
    "slug": "sports",
    "subcategories": [
      "Whey Protein & Nutrition",
      "Cricket Bats & Gear",
      "Badminton Rackets",
      "Yoga Mats",
      "Exercise Cycles & Dumbbells",
      "Camping & Outdoor"
    ]
  },
  {
    "icon": "Armchair",
    "id": "cat-furniture",
    "name": {
      "bn": "আসবাবপত্র",
      "en": "Furniture",
      "gu": "ફર્નિચર",
      "hi": "फर्नीचर",
      "mr": "फर्निचर",
      "or": "ଆସବାବପତ୍ର (ଫର୍ଣ୍ଣିଚର)",
      "ta": "மரச்சாமான்கள்",
      "te": "ఫర్నిచర్"
    },
    "slug": "furniture",
    "subcategories": [
      "Solid Wood Beds",
      "Wardrobes",
      "Ergonomic Study Chairs",
      "Dining Tables",
      "Recliners & Sofas",
      "TV Entertainment Units"
    ]
  },
  {
    "icon": "Cat",
    "id": "cat-pets",
    "name": {
      "bn": "পোষা প্রাণীর পণ্য",
      "en": "Pet Store",
      "gu": "પાલતુ પ્રાણીઓની દુકાન",
      "hi": "पालतू जानवरों की दुकान",
      "mr": "पाळीव प्राणी स्टोअर",
      "or": "ପୋଷା ଜନ୍ତୁ ସାମଗ୍ରୀ",
      "ta": "செல்லப்பிராணிகள் கடை",
      "te": "పెంపుడు జంతువుల దుకాణం"
    },
    "slug": "pets",
    "subcategories": [
      "Dog Food & Treats",
      "Cat Food & Toys",
      "Bird Food & Feeders",
      "Aquarium Care & Fish Food",
      "Grooming Shampoos"
    ]
  }
]
)SABKADATA");
}